---
title: "Data Manipulation"
author: "Wenxin Tian"
date: "`r Sys.Date()`"
output: html_document
---

```{r, message=FALSE}
library(tidyverse)
```

Importing FAS litters and pups dataset

```{r, results=FALSE, message=FALSE}
litters_df = 
  read_csv(file = "./data/FAS_litters.csv")

litters_df =
  janitor::clean_names(litters_df)

pups_df =
  read_csv("./data/FAS_pups.csv")

pups_df =
  janitor::clean_names(pups_df)
```

## Select

`select` is used to select variables, or __cols__.

```{r, results=FALSE}
select(litters_df, gd0_weight, group)

select(litters_df, -starts_with('gd')) #delete every variable starting with 'gd'

select(litters_df, -litter_number) #only leaving out litter_number

select(litters_df, group, litter_id = litter_number) #renaming litter_number to litter_id

select(litters_df, group, litter_id = litter_number, everything()) #leave everything not mentioned.

select(pups_df, litter_number, sex, pd_ears)

```

`select` vs. `pull`:

`select` will always return a dataframe, whereas `pull` could return a vector.

```{r}
select(litters_df, group)
pull(litters_df, group)
```

## Filter

Get rid of __rows__ using `filter()`

```{r}
filter(litters_df, group == 'Mod8') #only keeping rows that have Mod8 as group.

filter(litters_df, group != 'Con7')

filter(litters_df, gd0_weight > 20 | group == 'Con8') #using the 'or' operator

filter(litters_df, group %in% c("Con7", "Con8"))

filter(litters_df, group %in% c("Con7", "Con8"), gd0_weight > 20)
```

## Mutate

`mutate` is used to add or change variables.

```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight) #Adding new variable

mutate(litters_df, group = str_to_lower(group)) #changing all elements in 'group' to lower case

mutate(
  litters_df,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```

What about missing rows?

```{r}
drop_na(litters_df) #drop row if any element is NA

drop_na(litters_df, gd0_weight) #dropping a row only if it has NA on gd0_weight
```

## Arrange

```{r}
arrange(litters_df)

arrange(litters_df, group)

arrange(litters_df, group, gd0_weight)
```

## Pipes

Two operators, `|>` is used more commonly now, equivalent to `%>%`.

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv") |> 
  janitor::clean_names() |> 
  select(-starts_with('pups')) |> 
  mutate(
    group = str_to_lower(group),
    wt_gain = gd18_weight - gd0_weight
  ) |> 
  drop_na(wt_gain) |> 
  arrange(group, wt_gain)
litters_df
```

