---
title: "Tidy Data"
author: "Wenxin Tian"
date: "`r Sys.Date()`"
output: html_document
---

```{r, message=FALSE}
library(tidyverse)
```

## Pulse Data

```{r}
pulse_df = 
  haven::read_sas('data/public_pulse_data.sas7bdat') |>
  janitor::clean_names() |>
  pivot_longer( # convert from wide to long, move cols into rows
    bdi_score_bl:bdi_score_12m,
    names_to = 'visit', # variables -> observations
    values_to = 'bdi_score', # values -> new col
    names_prefix = 'bdi_score_',
  ) |>
  mutate(
    visit = replace(visit, visit == 'bl', '00m')
  )
```

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv") |> 
  janitor::clean_names() |>
  select(litter_number, gd0_weight, gd18_weight) |>
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = 'gd',
    values_to = 'weight'
  ) |>
  mutate(
    gd = case_match(
      gd, 
      "gd0_weight" ~ 0,
      "gd18_weight" ~ 18) # replace every gd0_weight with 0 and gd18_weight with 18
  )
```

## Lord of the Rings

Import LotR data:

```{r}
fellowship_df =
  readxl::read_excel('data/LotR_Words.xlsx', range = "B3:D6") |>
  mutate(movie = "fellowship")

two_towers_df =
  readxl::read_excel('data/LotR_Words.xlsx', range = "F3:H6") |>
  mutate(movie = "two towers")

return_of_the_king_df =
  readxl::read_excel('data/LotR_Words.xlsx', range = "J3:L6") |>
  mutate(movie = "return of the king")

lotr_df = 
  bind_rows(fellowship_df, two_towers_df, return_of_the_king_df) |>
  pivot_longer(
    Female:Male,
    names_to = "gender",
    values_to = "word"
  ) |>
  relocate(movie)
```

## Revisit FAS

Interested in weight gain
```{r}
litters_df = 
  read_csv('data/FAS_litters.csv') |>
  janitor::clean_names() |>
  mutate(wt_gain = gd18_weight - gd0_weight) |>
  select(litter_number, group, wt_gain) |>
  separate(group, into = c('dose', 'day_of_tx'), 3) # split 1 col into 2 cols

litters_df

pups_df =
  read_csv('data/FAS_pups.csv') |>
  janitor::clean_names() |>
  mutate(
    sex = case_match(
      sex,
      1 ~ 'male',
      2 ~ 'female'
    )
  )

pups_df

fas_df =
  left_join(pups_df, litters_df, by = 'litter_number')

fas_df
```

